### ISSUE TITLE
Character É

### ISSUE THREAD

**Issue by nataliaalves03** [larsenwork/Gidole#14]
Dear developer, 
Could you adjust the character "É"?
This one no apppears the accent on uppercase, but it works perfectly with lowercase.

Thanks for this great job! This font is awesome :)

Best.

**Comment by larsenwork** [comment]
thx, don't know how that happened but should be fixed 79e772e0e819191eff287a23512a1ef7ac9403b5

**Comment by larsenwork** [comment]
thx for the report

**Comment by nataliaalves03** [comment]
Thanks a lot!

2015-03-03 3:49 GMT-03:00 Andreas Larsen notifications@github.com:
