### ISSUE TITLE
Add tailed "l" glyph to both typefaces

### ISSUE THREAD

**Issue by inferno986return** [larsenwork/Gidole#16]
To make it a little closer to original DIN and ensure better legibility, why not add a tailed "l" similar to this one for both typefaces: http://myfonts.us/td-5p9XBr

I would personally prefer it as the default "l" glyph. But I would be just as happy with it available as a stylistic alternate.

**Comment by larsenwork** [comment]
it will be there as alternate at some point, yes

along with alternate g and maybe a couple of others
