### ISSUE TITLE
Add Oblique/Italic styles

### ISSUE THREAD

**Issue by inferno986return** [larsenwork/Gidole#18]
This is probably obvious, but I would love the inclusion of official oblique/italic styling. Particularly when the current Gidole Regular looks really readable at low sizes. Making it suitable for body text.

**Comment by larsenwork** [comment]
Yeah...it's fast too add "fake" obliques but I don't really want to do that (poor quality) and regular italics is something that will happen but weights, better spacing and a lot of other stuff has higher priority.
Rev2 that I'll release soon should be even more readable though :smile:

**Comment by CREEATION** [comment]
So waiting for this \o/ :heart:

**Comment by Copy33** [comment]
I'm waiting on bold :) is it coming soon?
Great font!

**Comment by larsenwork** [comment]
@Copy33 hoping to get time this christmas to look at it

**Comment by larsenwork** [comment]
merging this into wishlist issue
