### ISSUE TITLE
Alternate characters

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/Gidole#20]
**Drawing**
- [x] l with hook
- [x] i with hook
- [x] g that looks like :eyeglasses: 
- [x] u with stem
- [x] single story a
- [x] closed 4
- [x] curly y
- [x] Conventional @ sign
- [x] Dotted zero
- [ ] Curved 6
- [ ] Curved 9
- [ ] Old Style Numerals

Other suggestions?

**Comment by larsenwork** [comment]
Merging #17 #16 into this issue to keep them in the same place

**Comment by inferno986return** [comment]
A closed "4" glyph.

**Comment by inferno986return** [comment]
Also a single storey "a" glyph.

**Comment by larsenwork** [comment]
![screen shot 2015-03-19 at 12 51 40](https://cloud.githubusercontent.com/assets/3859425/6729837/bad2c738-ce36-11e4-82c6-79e4a19b6710.png)

Work in progress

**Comment by larsenwork** [comment]
Anyone know of a pretty way to make æ that matches the single storey a?

**Comment by larsenwork** [comment]
First draft g - not sure I'll spend too much time on it as I don't really think that style suits the typeface...maybe someone else can improve on it :)
![screen shot 2015-03-19 at 13 55 14](https://cloud.githubusercontent.com/assets/3859425/6730752/a620f81a-ce3f-11e4-9407-55e6c43ca6e7.png)

**Comment by inferno986return** [comment]
Excellent implementation so far. Especially the single storey "a", the stemmed "u", the tailed "l" and the alternate "y" glyphs. 

The "g" I am not so sure about, will definitely need a sample at a few sizes along with use in either words or sentences for me to determine if it's out of place.

Regarding the "æ" grapheme using a single storey "a". I did a quick search of notable typefaces that use a single storey "a" which are ITC Avant Garde Gothic, Futura and Helvetica SchoolBook.
1. ITC Avant Garde Gothic (http://myfonts.us/td-1sLQqV) and Helvetica SchoolBook (http://myfonts.us/td-x40SOU) use a single storey "a" grapheme. Personally I think it looks strange and foreign (then again being English I don't natively use it).
2. Futura (http://myfonts.us/td-ta7Y8V) doesn't bother at all and uses a standard spurless double storey "a" for the grapheme.

**Comment by larsenwork** [comment]
æ: Futura was also the first font I looked at and maybe something I'll try. Helvetica is a whole different style and the æ in ITC avant garde is definitely not drawn by someone who uses it themselves - I'm danish, so I use it and also why I'm maybe a bit picky about not just adding a different style just for the sake of it. 

g: very unsure myself. You can open this in a fontviewer (e.g. fontbook on mac) to see it (should be at the end) https://dl.dropboxusercontent.com/u/3019777/Gidole-Regular.ttf 

I have looked at the g in source sans pro for inspiration but it's too "caligraphic"

**Comment by larsenwork** [comment]
I think they blend in quite seamlessly :) uploaded version 2.0.1 with alternate a, l, y and u.
![screen shot 2015-03-19 at 16 06 20](https://cloud.githubusercontent.com/assets/3859425/6733338/ec45a928-ce51-11e4-8d5d-0cafb3528496.png)

**Comment by inferno986return** [comment]
With that preview in mind. I like the new "l".

**Comment by larsenwork** [comment]
About the "l" - I tried making the hook on the l a bit wider but didn't look right so I think I'll stick to this for now until someone suggests something better

**Comment by inferno986return** [comment]
I have thoroughly gone through that .ttf and I can't find the double storey "g".

Anyway I am very impressed by the PDF file. Well done on that, though grateful has only 1 "l" and sure has no "h" (quirks of the English language).

Looking through the PDF, I would love a more traditional "@" symbol to accompany the lovely new single storey "a" glyph.

Gidole is looking much better now. I love stylistic alternates! :-D

**Comment by larsenwork** [comment]
I always spell sure wrong...I blame the microphones...don't know where that extra l came from though, thanks for that!

Just updated https://dl.dropboxusercontent.com/u/3019777/Gidole-Regular.ttf so that g is now style set 5.

The alternate a definitely needs a different @, added to the list

**Comment by larsenwork** [comment]
First draft for the alt @ sign - I need to do something about the narrow curve from stem to big circle but other than that pretty happy.
![screen shot 2015-03-20 at 03 32 44](https://cloud.githubusercontent.com/assets/3859425/6745057/db0c2ae6-ceb1-11e4-805f-bfe7f228fd48.png)

**Comment by larsenwork** [comment]
A bit more rounded and in context:
![screen shot 2015-03-20 at 04 47 35](https://cloud.githubusercontent.com/assets/3859425/6745759/5e7efde0-cebc-11e4-9a3d-3632c3a113e3.png)

**Comment by larsenwork** [comment]
![ylu](https://cloud.githubusercontent.com/assets/3859425/6878307/3776220c-d4dc-11e4-97e6-fb76a8c43d10.png)

These might actually be the default characters - depending on how the vote over at #22 goes

**Comment by inferno986return** [comment]
Very impressive work. I took the liberty of viewing Gidole on FontBook for OS X. These alternate characters are coming along nicely.

I was wondering if I can add oldstyle text figures to the suggestion box.

**Comment by larsenwork** [comment]
Thx added to the list but probably no the first thing I'll make but who knows

**Comment by inferno986return** [comment]
Can I also add a tailed "i" to follow the tailed "l"? 

Similar to ITC Johnston: https://www.myfonts.com/fonts/itc/johnston/std-medium/glyphs.html#glyphs/538914/323

**Comment by larsenwork** [comment]
jup, should be quick to create

**Comment by larsenwork** [comment]
although the hook/tail should only be as big/long as on the l and not as in the example you've shown me, right?

**Comment by inferno986return** [comment]
I think that it will work if the tail is duplicated on the "i" glyph. Yeah.

Trying sampling it with the word "liability". :-)

**Comment by larsenwork** [comment]
merging this into a wishlist issue
