### ISSUE TITLE
Help me choose

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/Gidole#22]
I'll put different surveys here from time to time when I can't make up my mind.

**Help me pick the default "l", "y" and "u"**  
UPDATE: Vote has ended

**Comment by larsenwork** [comment]
thanks for the replies so far - would be great to hear from more people - it's pretty even :smile:

**Comment by Manuel-K** [comment]
I'm curious about this. Are you willing to share some preliminary results?

**Comment by larsenwork** [comment]
it is in favour of changing the defaults but not with a wide margin (can't remember exact numbers) 

I find it a bit interesting too since e.g. a straight l is good enough for both Apple and Google.

My thoughts so far:
curve y: yes
curve l: probably
stemmed u: probably not (I think it looks cleaner without and it doesn't increase legibility which both the curved y and l does

**Comment by Manuel-K** [comment]
I think the curve on the l is really important.

[@espiekermann](https://twitter.com/espiekermann/status/579240818206236672/photo/1) seems to think so, too. Although it could be his usual Helvetica bashing.

**Comment by larsenwork** [comment]
Yep, I've only just started designing fonts (Gidole is my first) so I haven't really gotten a "religious" opinion about it - although I like things as clean as possible.

And I'll probably end up adding it as default although slightly different design so it feels more at home with the current t but that discussion belongs in #25

**Comment by larsenwork** [comment]
Thanks for the votes, I ended changing the y and the l
**Results for anyone curious:**

<TABLE CELLSPACING="0" COLS="4" BORDER="0">
    <COLGROUP SPAN="3" WIDTH="68"></COLGROUP>
    <COLGROUP WIDTH="767"></COLGROUP>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>Which &quot;l&quot; should be default?</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>Which &quot;u&quot; should be default?</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>Which &quot;y&quot; should be default?</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>Optional comment</FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>I think the l without the hook is prettier, but the defaults should be usable for a body text and the version with the hook is more legible.</FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>with stem</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="87" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>Alternates would be good.<BR><BR>Hooked, stem and curvy seem to be the standard for lowercase in a DIN.<BR><BR>I like the simplicity of Gidole though. Just want more weights!</FONT></TD>
    </TR>
    <TR>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" HEIGHT="23" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>hooked</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>current</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2>curvy</FONT></TD>
        <TD STYLE="border-top: 1px solid #ffffff; border-bottom: 1px solid #ffffff; border-left: 1px solid #ffffff; border-right: 1px solid #ffffff" ALIGN="LEFT" VALIGN=BOTTOM><FONT FACE="Calibri" SIZE=2><BR></FONT></TD>
    </TR>
</TABLE>
