### ISSUE TITLE
OpenType Font file for Gidole (.otf)

### ISSUE THREAD

**Issue by inferno986return** [larsenwork/Gidole#23]
Would love am .otf file for Gidole on GitHub to complement the Gidolinya .otf file.

**Comment by larsenwork** [comment]
Is there any advantage over ttf?

**Comment by inferno986return** [comment]
It allows full support for all OpenType features including stylistic alternates, ligatures and small caps:

http://superuser.com/questions/96390/difference-between-otf-open-type-or-ttf-true-type-font-formats
http://www.typophile.com/node/94473

**Comment by larsenwork** [comment]
they are in the ttf file too ;) the extension doesn't tell you if it's truetype or opentype.
If you use the ttf file in e.g. indesign or other program you can choose stylistic set 1-5, fractions and slashed zero.
