### ISSUE TITLE
Typo in Readme+Characters.pdf

### ISSUE THREAD

**Issue by fitojb** [larsenwork/Gidole#24]
It says

> The OFL license let’s you do almost anything.

But that apostrophe is wrong. The development of _let’s_ is _let us_, which makes no sense here.

http://public.wsu.edu/~brians/errors/lets.html

I know I may be nitpicking, but these errors make the project look unprofessional :smiley_cat:

**Comment by larsenwork** [comment]
thx, nitpicking is all what this project is about :wink:

**Comment by larsenwork** [comment]
fixed in latest upload

**Comment by fitojb** [comment]
Thanks! :+1:
