### ISSUE TITLE
Additional glyphs...

### ISSUE THREAD

**Issue by Manuel-K** [larsenwork/Gidole#26]
I have a new item for the wishlist.

The interrobang (‽). I know it isn't a common punctuation mark, but it would be nice to have.

**Comment by larsenwork** [comment]
Is this good‽ 

![screen shot 2015-04-07 at 21 40 26](https://cloud.githubusercontent.com/assets/3859425/7031835/bb99b2d4-dd6e-11e4-9737-c2195e3c87ea.png)

Will be in the next update

**Comment by Manuel-K** [comment]
That was quick. A gap between the top of the exclamation mark and the question mark's curvature could make it easier to read. I really like the way Friedrich Althausen solved the problem:  
![Vollkorn](https://cloud.githubusercontent.com/assets/775439/7032198/6bfee12e-dd71-11e4-84ee-9a82c0170e12.png)

It appears as if a shortened version of the exclamation mark was inserted in a stretched (or rather distorted) version of the of the question mark. It seem like a very natural way.

I'm not sure if there is enough room for the characteristical widening of Gidole's exclamation mark without distorting the question mark.

.

**Comment by larsenwork** [comment]
![screen shot 2015-04-08 at 00 03 17](https://cloud.githubusercontent.com/assets/3859425/7034732/b284e63c-dd82-11e4-8fc6-94d9d8cffcef.png)

That could work too - not sure stretching is needed here since there's more space inside the ? and ! is narrower than the above example

**Comment by Manuel-K** [comment]
Nice.

**Comment by larsenwork** [comment]
:+1:
