### ISSUE TITLE
Monospace Gidole

### ISSUE THREAD

**Issue by renard** [larsenwork/Gidole#28]
Is a fixed width planed version of the Gidole font?

Thanks a lot!

**Comment by larsenwork** [comment]
I certainly want to add it at some point - how soon depends if I succeed in finding sponsors to support further/faster development ;)

**Comment by inferno986return** [comment]
I second the idea of a monospaced variant of Gidole. Would be lovely. :-)

**Comment by larsenwork** [comment]
@renard and @inferno986return you can try [monoid](http://larsen.work/monoid/) for now - it shares many traits with Gidole but works best at 14px only since it's drawn strictly over a grid

**Comment by renard** [comment]
Yes, nice job. the glyphs are very elegant.

Thanks a lot for your hard work!

**Comment by renard** [comment]
BTW just for curiosity, what is your workflow to design those fonts?

I can see you have one file per glyph. What do you use to edit those files? fontforge?

**Comment by larsenwork** [comment]
FontForge yes...you can also save as sfd but then you can't see what changes you've made in your source control (GitHub for my public projects) so that's why I prefer sfdir.

**Comment by larsenwork** [comment]
Like so: 
![screen shot 2015-06-03 at 18 30 11](https://cloud.githubusercontent.com/assets/3859425/7965555/99b71fb2-0a1e-11e5-976e-f4a1aa1bf61b.png)
