### ISSUE TITLE
Improve spacing and kerning

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/Gidole#3]
Would very much appreciate any help on this - even just short comments and suggestions like

```
r and ß are too close
```

:smile:

**Comment by jdittrich** [comment]
Could you briefly write which tools are needed to help here? Fontforge? Or is there any other preferred tool or toolchain?

**Comment by larsenwork** [comment]
Hi, thx for your interest.
I'm using Fontforge but I can easily update the UFO files if you're familiar with other font editors.
If you don't have any font editing experience then you can always help by going trough text strings and find errors.
I went from 1000 UPM to 2048 without really reviewing the spacing which should be adjusted first and then the kerning afterwards.

**Comment by jdittrich** [comment]
Thanks.
Some suggestions: 
![bildschirmfoto vom 2015-03-18 19 51 02](https://cloud.githubusercontent.com/assets/3416487/6717155/dac44904-cdaa-11e4-84a6-cfab78cf70ad.png)
"rf" too much space

![bildschirmfoto vom 2015-03-18 19 57 17](https://cloud.githubusercontent.com/assets/3416487/6717156/de898cca-cdaa-11e4-8575-7c971ce2fefa.png)
"ro" too wide/ "nd" too small (but just a tiny bit)

![bildschirmfoto vom 2015-03-18 19 57 37](https://cloud.githubusercontent.com/assets/3416487/6717159/e2fd4378-cdaa-11e4-9ccb-f86f7eb70385.png)
"rs" too wide/ "si" too wide, "io" too small (but just a tiny bit)

**Comment by larsenwork** [comment]
Thank you, I probably won't edit too much of the Gidolinya spacing right now since the whole font needs to be updated to match the new 2048 UPM Gidole - if you compare the two font's right now you can see that they have different metrics and many of the curves are different too.
And since redrawing it with a bigger UPM and slightly different curves screws up the spacing anyways it would be a bit futile to spend too much time on gidolinya right now, sorry for not being clear about that :smile: 

But I'll draw the updated Gidolinya based on the recent updated Gidole so any improvements there will benefit both. 

A general note about spacing - I generally stick to similar features having the same spacing (if I haven't made a mistake). In the example the spacing between nd, on and ou is the same so by suggesting adjusting nd change (which might well be needed) it will also affect the spacing between many other letters - i.e. all round+halfround combinations.

**Comment by larsenwork** [comment]
I'm currently fixing some over-kerned pairs but other than that I'm fairly satisfied so closing this for now.
