### ISSUE TITLE
Font as OTF

### ISSUE THREAD

**Issue by ghost** [larsenwork/Gidole#32]
Hi,
I know there is already a closed issue on this topic (#23), but I think I have some other reasons for the request.
I run Arch Linux + XFCE and is new to fonts. For me, the fonts available as OTF appear much better (a bit bolder; as you see in image below). So I cloned Gidole source and saved an OTF of Gidole-Regular using FontForge. But when using the generated OTF file, the font seems to shift position (base shifts a bit higher; as you see in image below) and looks misaligned (not vertically centered) in text fields.
![test](https://cloud.githubusercontent.com/assets/6317854/11299036/4e80fcf0-8fa9-11e5-938a-6cf0000f1b80.gif)
Am I doing it wrong using FontForge or are there some techicalities that I am missing (issues like how my system handles OTF etc.)? Would it be possible to provide a proper OTF file?
Thanks.

**Comment by larsenwork** [comment]
@frisbee00 I'm not on linux so I'm afraid it's difficult for me to debug. You can try using e.g. fontsquirrel webfont generator to create an otf version and see if you still have the problem http://www.fontsquirrel.com/tools/webfont-generator
