### ISSUE TITLE
Improve /&

### ISSUE THREAD

**Issue by larsenwork** [larsenwork/Gidole#5]
Not sure I'm satisfied with the current ampersand for Gidole Play  - suggestions more than welcome

**Comment by inferno986return** [comment]
Maybe offer the original ampersand as a stylistic alternate and have a more traditional ampersand as the default?

http://myfonts.us/td-04SY6X

**Comment by larsenwork** [comment]
@inferno986return hehe...I've actually already done that will upload when the revision is more or less done
![screen shot 2015-03-09 at 18 25 35](https://cloud.githubusercontent.com/assets/3859425/6560352/b2721292-c689-11e4-87ff-dfba4be0fbcd.png)
