### ISSUE TITLE
Why not include the web fonts? 

### ISSUE THREAD

**Issue by johncatley** [larsenwork/Gidole#9]
Since you use the web fonts on the nice website https://gidole.github.io why not include them in the repository?

**Comment by larsenwork** [comment]
I'll maybe add them at milestone 1.0 or if there were some way to automate the process. 

I only use rtf, woff and woff2 for the webpage - and don't update is as frequently so it's often a bit behind.

**Comment by larsenwork** [comment]
added now

**Comment by johncatley** [comment]
Thank you!
